version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: viberary-mysql
    restart: always
    environment:
      MYSQL_DATABASE: viberary_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - viberary-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: viberary-auth
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/viberary_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - viberary-net


  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: viberary-user
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/viberary_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - viberary-net

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/viberary_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - viberary-net

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: viberary-booking
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/viberary_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - viberary-net

  gateway:
    build: ./gateway
    container_name: viberary-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - book-service
      - booking-service
    networks:
      - viberary-net

  viberary-frontend:
    build:
      context: ./viberary-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - gateway
    networks:
      - viberary-net

volumes:
  mysql-data:

networks:
  viberary-net:
